---
version: '3'

services:
  postgres:
    image: postgres:12.3
    hostname: postgres-db
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: manager,cis,control
      POSTGRES_USER: "darko"
      POSTGRES_PASSWORD: "darko"
    volumes:
        # - /Users/darko/Documents/Projects/databases/parking-guidance:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
